### ISSUE TITLE
Speed on Titan X Pascal

### ISSUE THREAD

**Issue by lqfortytwo** [jcjohnson/fast-neural-style#16]
Hi! I tried to get the same time usage on as you. I tested it with image size 1024 on Titan X Pascal, and I also installed the cudnn. But I got the result around 1.5-2s.
`th fast_neural_style.lua \
  -model models/instance_norm/candy.t7 \
  -input_image images/content/chicago.jpg \
  -output_image out.png \
  -gpu 0`
Did I miss some parts? Should I use SSD?

**Comment by jcjohnson** [comment]
That sounds about right for the total runtime for a single image, since the script needs to load the model, load the image off disk, run the model through the image, and write the output back to disk. The first forward pass of the model is the slowest, since it allocates GPU memory lazily.

My timings are also with cuDNN benchmark mode turned on, which is disabled by default; this automatically runs experiments to select the best cuDNN algorithm for each conv layer which makes the first forward pass much slower but can give significant speedups on subsequent calls.

To reproduce my results, try adding the flags `-cudnn_benchmark 1` to enable cuDNN benchmark mode and `-timing 1` for more accurate timings; this will run an extra forward pass to warm up GPU memory and cuDNN, and will print the time it took to run the image through the model.

**Comment by lqfortytwo** [comment]
Awesome! Thank you very much!
