### ISSUE TITLE
Fast-neural-style and artistic-videos Not An Issue

### ISSUE THREAD

**Issue by jbgrant01** [jcjohnson/fast-neural-style#67]
First off great work on fast-neural-style. I haven't been successful in training a model, but you and the others here have been very helpful.

I have been trying to figure out how to use your code within Manual Ruder's artistic-videos. It appears he passes an optical/temporal flow layer to the original neural-style neural net and then processes the frame through the net.

I was wondering if it would be possible to add a layer to a copy of a .t7 model (such as la_muse.t7) for optical flow, dynamically updating the model for each frame and then processing the frame with fast-neural-style. My question is whether it would be feasible to insert a layer into the model and whether one set of values in the layer would have any effect on the image. It is likely the two objects (neural-style neural net and the .t7 model) are too dissimilar for this to be feasible.

Thanks for any information. Keep up your incredible work.

**Comment by jcjohnson** [comment]
artistic-videos uses an optimization-based approach: it solves an optimization problem to synthesize each video frame, and this optimization problems includes terms incorporating optical flow information.

In contrast, fast-neural-style trains a feedforward model specific to a single style, so that images can be synthesized with a single forward pass of the model.

Combining the two would look like some sort of feedforward model that used optical flow information for temporal consistency. I'm not aware of anybody who has done this, so it is an open research problem. I suspect that it is possible, but I'm not sure what the right approach would be.

**Comment by jbgrant01** [comment]
Thanks for your quick response. I am a photo/video/computer hobbyist, not a researcher. I will look at how the .t7 models update in training and try to see if an original neural-style neural net layer could add a layer to the model. Is there a good reference website on the technical specs on the .t7 models? I imagine there would be some padding and tweaking involved.

**Comment by jbgrant01** [comment]
Found some websites on creating and training models. Thanks again for your work here.
